# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: abstract class {...}

description: Abstract Class, Blog of Anindya Chatterjee
author:
  name: Anindya Chatterjee
  email: anidotnet@gmail.com
  github: anidotnet
  twitter: anidotnet
  #pinterest: asd123
  linkedin: anidotnet
  bio: Blog of Anindya Chatterjee!
  email_md5: 9c74f9c66df98052bef13864bffcd09c

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
